name: pr-size

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@54ef36785e9f4cb5ecf1949cfc9b00dbb621d761 # v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/xs'
          xs_max_size: '10'
          s_label: 'size/s'
          s_max_size: '200'
          m_label: 'size/m'
          m_max_size: '1000'
          l_label: 'size/l'
          l_max_size: '10000'
          xl_label: 'size/xl'
          fail_if_xl: 'false'
          # An empty string disables this
          message_if_xl: ''
          github_api_url: 'https://api.github.com'
          files_to_ignore: |
            "package-lock.json"
            "go.sum"
            "runatlantis.io/*"
            "pnpm-lock.yml"
